### PR TITLE
Using multiple RMII Ethernet PHYs in one SoC design

### PR DESCRIPTION
**Pull request by rprinz08**
Hello,

the following two patches allow to use more than one RMII Ethernet PHY and the use of RMII PHY modules which do not use a "rst_n" signal. I didn't find a way of doing this without these two patches ...

Additional infos about the design:
[https://github.com/rprinz08/arty-s7-multinic](https://github.com/rprinz08/arty-s7-multinic)
and
[https://www.min.at/prinz/?x=entry:entry200428-150015](https://www.min.at/prinz/?x=entry:entry200428-150015)

br
Richard

### CODE REVIEW

**Comment by enjoy-digital** [comment]
Hello,

thanks for the PR and sharing your project, very interesting! We can probably simplify things using `ClockDomainsRenamer`, i'll have a closer look in the next days.

Florent

**Comment by enjoy-digital** [comment]
Sorry, time is flying, i'll try to review this soon.

**Comment by rprinz08** [comment]
No problem. Had to add another change about generating clock output.

**Comment by mwick83** [comment]
What's the status of this issue/patchset? I just ran into the same issue, that it is impossible to add multiple phys to my SoC.

**Comment by enjoy-digital** [comment]
@rprinz08, @mwick83: sorry for the delay on this. This hasn't been merged since things can be done in a simpler way but I haven't spend the time to have a closer look at this until now. Instead of adding` cd_tx_name` and `cd_rx_name`, we can just use `ClockDomainsRenamer` on the core as done here: https://github.com/enjoy-digital/litex/commit/12dabde77c87de0528f6424f87c231da657d1fc8

And then do the integration like this:

```diff
diff --git a/litex_boards/platforms/netv2.py b/litex_boards/platforms/netv2.py
index 8b27be4..8ae779a 100644
--- a/litex_boards/platforms/netv2.py
+++ b/litex_boards/platforms/netv2.py
@@ -120,6 +120,23 @@ _io = [
         IOStandard("LVCMOS33")
      ),
 
+    ("eth_clocks", 1,
+        Subsignal("ref_clk", Pins("D17")),
+        IOStandard("LVCMOS33"),
+    ),
+    ("eth", 1,
+        Subsignal("rst_n",   Pins("F16")),
+        Subsignal("rx_data", Pins("A20 B18")),
+        Subsignal("crs_dv",  Pins("C20")),
+        Subsignal("tx_en",   Pins("A19")),
+        Subsignal("tx_data", Pins("C18 C19")),
+        Subsignal("mdc",     Pins("F14")),
+        Subsignal("mdio",    Pins("F13")),
+        Subsignal("rx_er",   Pins("B20")),
+        Subsignal("int_n",   Pins("D21")),
+        IOStandard("LVCMOS33")
+     ),
+
      # SDCard
     ("spisdcard", 0,
         Subsignal("clk",  Pins("K18")),
diff --git a/litex_boards/targets/netv2.py b/litex_boards/targets/netv2.py
index cf11687..b2bf9f2 100755
--- a/litex_boards/targets/netv2.py
+++ b/litex_boards/targets/netv2.py
@@ -92,11 +92,17 @@ class BaseSoC(SoCCore):
 
         # Ethernet ---------------------------------------------------------------------------------
         if with_ethernet:
-            self.submodules.ethphy = LiteEthPHYRMII(
-                clock_pads = self.platform.request("eth_clocks"),
-                pads       = self.platform.request("eth"))
-            self.add_csr("ethphy")
-            self.add_ethernet(phy=self.ethphy)
+            self.submodules.ethphy0 = LiteEthPHYRMII(
+                clock_pads = self.platform.request("eth_clocks", 0),
+                pads       = self.platform.request("eth", 0))
+            self.add_csr("ethphy0")
+            self.add_ethernet(name="ethmac0", phy=self.ethphy0, phy_cd="ethphy0_eth")
+
+            self.submodules.ethphy1 = LiteEthPHYRMII(
+                clock_pads = self.platform.request("eth_clocks", 1),
+                pads       = self.platform.request("eth", 1))
+            self.add_csr("ethphy1")
+            self.add_ethernet(name="ethmac1", phy=self.ethphy1, phy_cd="ethphy1_eth")
 
         # PCIe -------------------------------------------------------------------------------------
         if with_pcie:
```

I also recently made `pads.rst_n` optional on all PHYs, so the other issue with `pads.rst_n` shared between the two PHYs should also be solved.

Note that the proposed solution only allows building valid hardware. The BIOS is currently only supporting one Ethernet PHY and this is not yet decided if we'll support multiple instances in the BIOS or it will have to be done with multiple  SoCs.

**Comment by mwick83** [comment]
That's great, thanks! I had to add a clock domain renaming to the phy as well to make it work if only one of the phys is added (but the MAC uses a non-default name).

**Pull request closed without merging**
