### PR TITLE
Add practical FPGA example to /example/targets/versa_ecp5_udp_loopback

### PR DESCRIPTION
**Pull request by BracketMaster**
I added a practical ecp5 FPGA example with a quick tutorial on how to instantiate an UDP ethernet core from what I learned while using Liteeth. I hope others can benefit.
I also added myself to CONTRIBUTORS.
Lastly, I point to this example in the getting started part of the main README.

### CODE REVIEW

**Comment by enjoy-digital** [comment]
Hi BracketMaster,

thanks this is a good example Would mind just changing the ip-addresses of the example to `192.168.1.50` for the FPGA and `192.168.1.100` for the Host to keep consistency with the others LiteX examples?

**Comment by BracketMaster** [comment]
I can do that.

**Comment by BracketMaster** [comment]
Done. Lemme know if it looks good.

**Comment by enjoy-digital** [comment]
Thanks, this as been integrated and reworked a little bit with https://github.com/enjoy-digital/liteeth/pull/23.  (You'll probably have to update a little bit your tutorial if you don't have another copy of it in your tutorial and expect it to be here).

**Pull request closed without merging**
