### PR TITLE
ecp5rgmii: enable reading inband PHY_status

### PR DESCRIPTION
**Pull request by shuffle2**
I've tried to do it in a way that could be used by other rgmii modules...

If supported by phy, this is much more convenient than mdio

### CODE REVIEW

**Comment by enjoy-digital** [comment]
Thanks, i'll review it in the next days, can you fix the copyrights in `rgmii.py` (put yours).

**Comment by shuffle2** [comment]
> Thanks, i'll review it in the next days, can you fix the copyrights in `rgmii.py` (put yours).

done

**Comment by enjoy-digital** [comment]
Thanks for the PR! It's merged but has been refactored with https://github.com/enjoy-digital/liteeth/commit/8afdec936dd404fcade66fe4d0eb507e447fa2b1. I've been able to test it on a Versa ECP5 board. Can you check this is ok for you? (the inband status are exposed to a CSR, if you want to access if from the logic, the fields can be accessed: `phy.rx.inband_status.fields.link_status`, `phy.rx.inband_status.fields.clock_speed`, etc...

**Comment by shuffle2** [comment]
seems to work fine here, thanks :)

**Pull request merged**
